/**
 * Various default Helper classes
 */
package taack.ui.config

import groovy.transform.CompileStatic
import taack.ui.EnumOption

@CompileStatic
final enum Continent {
    AF(30_065_000, 1_216_130_000),
    AN(13_209_000, 1_500),
    AS(44_579_000, 4_436_224_000),
    EU(9_938_000, 738_849_000),
    NA(24_256_000, 410_013_492),
    OC(7_687_000, 39_901_000),
    SA(17_819_000, 410_013_492)

    Continent(final int areaKm2, final long population) {
        this.areaKm2 = areaKm2
        this.population = population
    }

    final int areaKm2
    final long population
}

@CompileStatic
final enum ContinentCountries {
    DZ(Continent.AF),
    AO(Continent.AF),
    BW(Continent.AF),
    IO(Continent.AF),
    BI(Continent.AF),
    CM(Continent.AF),
    CV(Continent.AF),
    CF(Continent.AF),
    TD(Continent.AF),
    KM(Continent.AF),
    YT(Continent.AF),
    CG(Continent.AF),
    CD(Continent.AF),
    BJ(Continent.AF),
    GQ(Continent.AF),
    ET(Continent.AF),
    ER(Continent.AF),
    TF(Continent.AF),
    DJ(Continent.AF),
    GA(Continent.AF),
    GM(Continent.AF),
    GH(Continent.AF),
    GN(Continent.AF),
    CI(Continent.AF),
    KE(Continent.AF),
    LS(Continent.AF),
    LR(Continent.AF),
    LY(Continent.AF),
    MG(Continent.AF),
    MW(Continent.AF),
    ML(Continent.AF),
    MR(Continent.AF),
    MU(Continent.AF),
    MA(Continent.AF),
    MZ(Continent.AF),
    NA(Continent.AF),
    NE(Continent.AF),
    NG(Continent.AF),
    GW(Continent.AF),
    RE(Continent.AF),
    RW(Continent.AF),
    SH(Continent.AF),
    ST(Continent.AF),
    SN(Continent.AF),
    SC(Continent.AF),
    SL(Continent.AF),
    SO(Continent.AF),
    ZA(Continent.AF),
    ZW(Continent.AF),
    SS(Continent.AF),
    SD(Continent.AF),
    EH(Continent.AF),
    SZ(Continent.AF),
    TG(Continent.AF),
    TN(Continent.AF),
    UG(Continent.AF),
    TZ(Continent.AF),
    BF(Continent.AF),
    ZM(Continent.AF),
    AQ(Continent.AN),
    BV(Continent.AN),
    GS(Continent.AN),
    HM(Continent.AN),
    AF(Continent.AS),
    BH(Continent.AS),
    BD(Continent.AS),
    BT(Continent.AS),
    BN(Continent.AS),
    MM(Continent.AS),
    KH(Continent.AS),
    LK(Continent.AS),
    CN(Continent.AS),
    TW(Continent.AS),
    CX(Continent.AS),
    CC(Continent.AS),
    HK(Continent.AS),
    IN(Continent.AS),
    ID(Continent.AS),
    IR(Continent.AS),
    IQ(Continent.AS),
    IL(Continent.AS),
    JP(Continent.AS),
    JO(Continent.AS),
    KP(Continent.AS),
    KR(Continent.AS),
    KW(Continent.AS),
    KG(Continent.AS),
    LA(Continent.AS),
    LB(Continent.AS),
    MO(Continent.AS),
    MY(Continent.AS),
    MV(Continent.AS),
    MN(Continent.AS),
    OM(Continent.AS),
    NP(Continent.AS),
    PK(Continent.AS),
    PS(Continent.AS),
    PH(Continent.AS),
    TL(Continent.AS),
    QA(Continent.AS),
    SA(Continent.AS),
    SG(Continent.AS),
    VN(Continent.AS),
    SY(Continent.AS),
    TJ(Continent.AS),
    TH(Continent.AS),
    AE(Continent.AS),
    TM(Continent.AS),
    EG(Continent.AS),
    UZ(Continent.AS),
    YE(Continent.AS),
    XD(Continent.AS),
    XS(Continent.AS),
    AL(Continent.EU),
    AD(Continent.EU),
    AZ(Continent.EU),
    AT(Continent.EU),
    AM(Continent.EU),
    BE(Continent.EU),
    BA(Continent.EU),
    BG(Continent.EU),
    BY(Continent.EU),
    HR(Continent.EU),
    CY(Continent.EU),
    CZ(Continent.EU),
    DK(Continent.EU),
    EE(Continent.EU),
    FO(Continent.EU),
    FI(Continent.EU),
    AX(Continent.EU),
    FR(Continent.EU),
    GE(Continent.EU),
    DE(Continent.EU),
    GI(Continent.EU),
    GR(Continent.EU),
    VA(Continent.EU),
    HU(Continent.EU),
    IS(Continent.EU),
    IE(Continent.EU),
    IT(Continent.EU),
    KZ(Continent.EU),
    XK(Continent.EU),
    LV(Continent.EU),
    LI(Continent.EU),
    LT(Continent.EU),
    LU(Continent.EU),
    MT(Continent.EU),
    MC(Continent.EU),
    MD(Continent.EU),
    ME(Continent.EU),
    NL(Continent.EU),
    NO(Continent.EU),
    PL(Continent.EU),
    FL(Continent.EU),
    PT(Continent.EU),
    RO(Continent.EU),
    RU(Continent.EU),
    SM(Continent.EU),
    RS(Continent.EU),
    SK(Continent.EU),
    SI(Continent.EU),
    ES(Continent.EU),
    SJ(Continent.EU),
    SE(Continent.EU),
    CH(Continent.EU),
    TR(Continent.EU),
    UA(Continent.EU),
    MK(Continent.EU),
    GB(Continent.EU),
    GG(Continent.EU),
    JE(Continent.EU),
    IM(Continent.EU),
    AG(Continent.NA),
    BS(Continent.NA),
    BB(Continent.NA),
    BM(Continent.NA),
    BZ(Continent.NA),
    VG(Continent.NA),
    CA(Continent.NA),
    KY(Continent.NA),
    CR(Continent.NA),
    CU(Continent.NA),
    DM(Continent.NA),
    DO(Continent.NA),
    SV(Continent.NA),
    GL(Continent.NA),
    GD(Continent.NA),
    GP(Continent.NA),
    GT(Continent.NA),
    HT(Continent.NA),
    HN(Continent.NA),
    JM(Continent.NA),
    MQ(Continent.NA),
    MX(Continent.NA),
    MS(Continent.NA),
    CW(Continent.NA),
    AW(Continent.NA),
    SX(Continent.NA),
    BQ(Continent.NA),
    NI(Continent.NA),
    PA(Continent.NA),
    PR(Continent.NA),
    BL(Continent.NA),
    KN(Continent.NA),
    AI(Continent.NA),
    LC(Continent.NA),
    MF(Continent.NA),
    PM(Continent.NA),
    VC(Continent.NA),
    TT(Continent.NA),
    TC(Continent.NA),
    US(Continent.NA),
    VI(Continent.NA),
    AS(Continent.OC),
    AU(Continent.OC),
    SB(Continent.OC),
    CK(Continent.OC),
    FJ(Continent.OC),
    PF(Continent.OC),
    KI(Continent.OC),
    GU(Continent.OC),
    NR(Continent.OC),
    NC(Continent.OC),
    VU(Continent.OC),
    NZ(Continent.OC),
    NU(Continent.OC),
    NF(Continent.OC),
    MP(Continent.OC),
    UM(Continent.OC),
    FM(Continent.OC),
    MH(Continent.OC),
    PW(Continent.OC),
    PG(Continent.OC),
    PN(Continent.OC),
    TK(Continent.OC),
    TO(Continent.OC),
    TV(Continent.OC),
    WF(Continent.OC),
    WS(Continent.OC),
    XX(Continent.OC),
    AR(Continent.SA),
    BO(Continent.SA),
    BR(Continent.SA),
    CL(Continent.SA),
    CO(Continent.SA),
    EC(Continent.SA),
    FK(Continent.SA),
    GF(Continent.SA),
    GY(Continent.SA),
    PY(Continent.SA),
    PE(Continent.SA),
    SR(Continent.SA),
    UY(Continent.SA),
    VE(Continent.SA)

    ContinentCountries(final Continent continent) {
        this.continent = continent
    }
    
    final Continent continent
}

@CompileStatic
enum Country {
    AF(Continent.AF, "Afghanistan", "AF", "AFG", 4, 33f),
    AL(Continent.AF, "Albania", "AL", "ALB", 8, 41f),
    DZ(Continent.AF, "Algeria", "DZ", "DZA", 12, 28f),
    AS(Continent.AF, "American Samoa", "AS", "ASM", 16, -14.3333f),
    AD(Continent.AF, "Andorra", "AD", "AND", 20, 42.5f),
    AO(Continent.AF, "Angola", "AO", "AGO", 24, -12.5f),
    AI(Continent.AF, "Anguilla", "AI", "AIA", 660, 18.25f),
    AQ(Continent.AF, "Antarctica", "AQ", "ATA", 10, -90f),
    AG(Continent.AF, "Antigua and Barbuda", "AG", "ATG", 28, 17.05f),
    AR(Continent.AF, "Argentina", "AR", "ARG", 32, -34f),
    AM(Continent.AF, "Armenia", "AM", "ARM", 51, 40f),
    AW(Continent.AF, "Aruba", "AW", "ABW", 533, 12.5f),
    AU(Continent.AF, "Australia", "AU", "AUS", 36, -27f),
    AT(Continent.AF, "Austria", "AT", "AUT", 40, 47.3333f),
    AZ(Continent.AF, "Azerbaijan", "AZ", "AZE", 31, 40.5f),
    BS(Continent.AF, "Bahamas", "BS", "BHS", 44, 24.25f),
    BH(Continent.AF, "Bahrain", "BH", "BHR", 48, 26f),
    BD(Continent.AF, "Bangladesh", "BD", "BGD", 50, 24f),
    BB(Continent.AF, "Barbados", "BB", "BRB", 52, 13.1667f),
    BY(Continent.AF, "Belarus", "BY", "BLR", 112, 53f),
    BE(Continent.AF, "Belgium", "BE", "BEL", 56, 50.8333f),
    BZ(Continent.AF, "Belize", "BZ", "BLZ", 84, 17.25f),
    BJ(Continent.AF, "Benin", "BJ", "BEN", 204, 9.5f),
    BM(Continent.AF, "Bermuda", "BM", "BMU", 60, 32.3333f),
    BT(Continent.AF, "Bhutan", "BT", "BTN", 64, 27.5f),
    BO(Continent.AF, "Bolivia", "BO", "BOL", 68, -17f),
    BA(Continent.AF, "Bosnia and Herzegovina", "BA", "BIH", 70, 44f),
    BW(Continent.AF, "Botswana", "BW", "BWA", 72, -22f),
    BV(Continent.AF, "Bouvet Island", "BV", "BVT", 74, -54.4333f),
    BR(Continent.AF, "Brazil", "BR", "BRA", 76, -10f),
    IO(Continent.AF, "British Indian Ocean Territory", "IO", "IOT", 86, -6f),
    BN(Continent.AF, "Brunei", "BN", "BRN", 96, 4.5f),
    BG(Continent.AF, "Bulgaria", "BG", "BGR", 100, 43f),
    BF(Continent.AF, "Burkina Faso", "BF", "BFA", 854, 13f),
    BI(Continent.AF, "Burundi", "BI", "BDI", 108, -3.5f),
    KH(Continent.AF, "Cambodia", "KH", "KHM", 116, 13f),
    CM(Continent.AF, "Cameroon", "CM", "CMR", 120, 6f),
    CA(Continent.AF, "Canada", "CA", "CAN", 124, 60f),
    CV(Continent.AF, "Cape Verde", "CV", "CPV", 132, 16f),
    CS(Continent.AF, "Czechoslovakia", "CS", "CSK", 132, 16f),
    KY(Continent.AF, "Cayman Islands", "KY", "CYM", 136, 19.5f),
    CF(Continent.AF, "Central African Republic", "CF", "CAF", 140, 7f),
    TD(Continent.AF, "Chad", "TD", "TCD", 148, 15f),
    CL(Continent.AF, "Chile", "CL", "CHL", 152, -30f),
    CN(Continent.AF, "China", "CN", "CHN", 156, 35f),
    CX(Continent.AF, "Christmas Island", "CX", "CXR", 162, -10.5f),
    CC(Continent.AF, "Cocos (Keeling) Islands", "CC", "CCK", 166, -12.5f),
    CO(Continent.AF, "Colombia", "CO", "COL", 170, 4f),
    CW(Continent.AF, "Curaçao", "CW", "CUW", 170, 4f),
    KM(Continent.AF, "Comoros", "KM", "COM", 174, -12.1667f),
    CG(Continent.AF, "Congo", "CG", "COG", 178, -1f),
    CD(Continent.AF, "Congo, the Democratic Republic of the", "CD", "COD", 180, 0f),
    CK(Continent.AF, "Cook Islands", "CK", "COK", 184, -21.2333f),
    CR(Continent.AF, "Costa Rica", "CR", "CRI", 188, 10f),
    CI(Continent.AF, "Ivory Coast", "CI", "CIV", 384, 8f),
    HR(Continent.AF, "Croatia", "HR", "HRV", 191, 45.1667f),
    CU(Continent.AF, "Cuba", "CU", "CUB", 192, 21.5f),
    CY(Continent.AF, "Cyprus", "CY", "CYP", 196, 35f),
    CZ(Continent.AF, "Czech Republic", "CZ", "CZE", 203, 49.75f),
    DK(Continent.AF, "Denmark", "DK", "DNK", 208, 56f),
    DJ(Continent.AF, "Djibouti", "DJ", "DJI", 262, 11.5f),
    DM(Continent.AF, "Dominica", "DM", "DMA", 212, 15.4167f),
    DO(Continent.AF, "Dominican Republic", "DO", "DOM", 214, 19f),
    EC(Continent.AF, "Ecuador", "EC", "ECU", 218, -2f),
    EG(Continent.AF, "Egypt", "EG", "EGY", 818, 27f),
    SV(Continent.AF, "El Salvador", "SV", "SLV", 222, 13.8333f),
    GQ(Continent.AF, "Equatorial Guinea", "GQ", "GNQ", 226, 2f),
    ER(Continent.AF, "Eritrea", "ER", "ERI", 232, 15f),
    EE(Continent.AF, "Estonia", "EE", "EST", 233, 59f),
    ET(Continent.AF, "Ethiopia", "ET", "ETH", 231, 8f),
    FK(Continent.AF, "Falkland Islands (Malvinas)", "FK", "FLK", 238, -51.75f),
    FO(Continent.AF, "Faroe Islands", "FO", "FRO", 234, 62f),
    FJ(Continent.AF, "Fiji", "FJ", "FJI", 242, -18f),
    FI(Continent.AF, "Finland", "FI", "FIN", 246, 64f),
    FL(Continent.AF, "Liechtenstein", "FL", "LIE", 47, 9.55f),
    FR(Continent.AF, "France", "FR", "FRA", 250, 46f),
    GF(Continent.AF, "French Guiana", "GF", "GUF", 254, 4f),
    PF(Continent.AF, "French Polynesia", "PF", "PYF", 258, -15f),
    TF(Continent.AF, "French Southern Territories", "TF", "ATF", 260, -43f),
    GA(Continent.AF, "Gabon", "GA", "GAB", 266, -1f),
    GM(Continent.AF, "Gambia", "GM", "GMB", 270, 13.4667f),
    GE(Continent.AF, "Georgia", "GE", "GEO", 268, 42f),
    DE(Continent.AF, "Germany", "DE", "DEU", 276, 51f),
    GH(Continent.AF, "Ghana", "GH", "GHA", 288, 8f),
    GI(Continent.AF, "Gibraltar", "GI", "GIB", 292, 36.1833f),
    GR(Continent.AF, "Greece", "GR", "GRC", 300, 39f),
    GL(Continent.AF, "Greenland", "GL", "GRL", 304, 72f),
    GD(Continent.AF, "Grenada", "GD", "GRD", 308, 12.1167f),
    GP(Continent.AF, "Guadeloupe", "GP", "GLP", 312, 16.25f),
    GU(Continent.AF, "Guam", "GU", "GUM", 316, 13.4667f),
    GT(Continent.AF, "Guatemala", "GT", "GTM", 320, 15.5f),
    GG(Continent.AF, "Guernsey", "GG", "GGY", 831, 49.5f),
    GN(Continent.AF, "Guinea", "GN", "GIN", 324, 11f),
    GW(Continent.AF, "Guinea-Bissau", "GW", "GNB", 624, 12f),
    GY(Continent.AF, "Guyana", "GY", "GUY", 328, 5f),
    HT(Continent.AF, "Haiti", "HT", "HTI", 332, 19f),
    HM(Continent.AF, "Heard Island and McDonald Islands", "HM", "HMD", 334, -53.1f),
    VA(Continent.AF, "Holy See (Vatican City State)", "VA", "VAT", 336, 41.9f),
    HN(Continent.AF, "Honduras", "HN", "HND", 340, 15f),
    HK(Continent.AF, "Hong Kong", "HK", "HKG", 344, 22.25f),
    HU(Continent.AF, "Hungary", "HU", "HUN", 348, 47f),
    IS(Continent.AF, "Iceland", "IS", "ISL", 352, 65f),
    IN(Continent.AF, "India", "IN", "IND", 356, 20f),
    ID(Continent.AF, "Indonesia", "ID", "IDN", 360, -5f),
    IR(Continent.AF, "Iran, Islamic Republic of", "IR", "IRN", 364, 32f),
    IQ(Continent.AF, "Iraq", "IQ", "IRQ", 368, 33f),
    IE(Continent.AF, "Ireland", "IE", "IRL", 372, 53f),
    IM(Continent.AF, "Isle of Man", "IM", "IMN", 833, 54.23f),
    IL(Continent.AF, "Israel", "IL", "ISR", 376, 31.5f),
    IT(Continent.AF, "Italy", "IT", "ITA", 380, 42.8333f),
    JM(Continent.AF, "Jamaica", "JM", "JAM", 388, 18.25f),
    JP(Continent.AF, "Japan", "JP", "JPN", 392, 36f),
    JE(Continent.AF, "Jersey", "JE", "JEY", 832, 49.21f),
    JO(Continent.AF, "Jordan", "JO", "JOR", 400, 31f),
    KZ(Continent.AF, "Kazakhstan", "KZ", "KAZ", 398, 48f),
    KE(Continent.AF, "Kenya", "KE", "KEN", 404, 1f),
    KI(Continent.AF, "Kiribati", "KI", "KIR", 296, 1.4167f),
    KP(Continent.AF, "Korea, Democratic People's Republic of", "KP", "PRK", 408, 40f),
    KR(Continent.AF, "South Korea", "KR", "KOR", 410, 37f),
    KW(Continent.AF, "Kuwait", "KW", "KWT", 414, 29.3375f),
    KG(Continent.AF, "Kyrgyzstan", "KG", "KGZ", 417, 41f),
    LA(Continent.AF, "Lao People's Democratic Republic", "LA", "LAO", 418, 18f),
    LV(Continent.AF, "Latvia", "LV", "LVA", 428, 57f),
    LB(Continent.AF, "Lebanon", "LB", "LBN", 422, 33.8333f),
    LS(Continent.AF, "Lesotho", "LS", "LSO", 426, -29.5f),
    LR(Continent.AF, "Liberia", "LR", "LBR", 430, 6.5f),
    LY(Continent.AF, "Libya", "LY", "LBY", 434, 25f),
    LI(Continent.AF, "Liechtenstein", "LI", "LIE", 438, 47.1667f),
    LT(Continent.AF, "Lithuania", "LT", "LTU", 440, 56f),
    LU(Continent.AF, "Luxembourg", "LU", "LUX", 442, 49.75f),
    MO(Continent.AF, "Macao", "MO", "MAC", 446, 22.1667f),
    MK(Continent.AF, "Macedonia, the former Yugoslav Republic of", "MK", "MKD", 807, 41.8333f),
    MG(Continent.AF, "Madagascar", "MG", "MDG", 450, -20f),
    MW(Continent.AF, "Malawi", "MW", "MWI", 454, -13.5f),
    MY(Continent.AF, "Malaysia", "MY", "MYS", 458, 2.5f),
    MV(Continent.AF, "Maldives", "MV", "MDV", 462, 3.25f),
    ML(Continent.AF, "Mali", "ML", "MLI", 466, 17f),
    MT(Continent.AF, "Malta", "MT", "MLT", 470, 35.8333f),
    MH(Continent.AF, "Marshall Islands", "MH", "MHL", 584, 9f),
    MQ(Continent.AF, "Martinique", "MQ", "MTQ", 474, 14.6667f),
    MR(Continent.AF, "Mauritania", "MR", "MRT", 478, 20f),
    MU(Continent.AF, "Mauritius", "MU", "MUS", 480, -20.2833f),
    YT(Continent.AF, "Mayotte", "YT", "MYT", 175, -12.8333f),
    MX(Continent.AF, "Mexico", "MX", "MEX", 484, 23f),
    FM(Continent.AF, "Micronesia, Federated States of", "FM", "FSM", 583, 6.9167f),
    MD(Continent.AF, "Moldova, Republic of", "MD", "MDA", 498, 47f),
    MC(Continent.AF, "Monaco", "MC", "MCO", 492, 43.7333f),
    MN(Continent.AF, "Mongolia", "MN", "MNG", 496, 46f),
    ME(Continent.AF, "Montenegro", "ME", "MNE", 499, 42f),
    MS(Continent.AF, "Montserrat", "MS", "MSR", 500, 16.75f),
    MA(Continent.AF, "Morocco", "MA", "MAR", 504, 32f),
    MZ(Continent.AF, "Mozambique", "MZ", "MOZ", 508, -18.25f),
    MM(Continent.AF, "Burma", "MM", "MMR", 104, 22f),
    NA(Continent.AF, "Namibia", "NA", "NAM", 516, -22f),
    NR(Continent.AF, "Nauru", "NR", "NRU", 520, -0.5333f),
    NP(Continent.AF, "Nepal", "NP", "NPL", 524, 28f),
    NL(Continent.AF, "Netherlands", "NL", "NLD", 528, 52.5f),
    AN(Continent.AF, "Netherlands Antilles", "AN", "ANT", 530, 12.25f),
    NC(Continent.AF, "New Caledonia", "NC", "NCL", 540, -21.5f),
    NZ(Continent.AF, "New Zealand", "NZ", "NZL", 554, -41f),
    NI(Continent.AF, "Nicaragua", "NI", "NIC", 558, 13f),
    NE(Continent.AF, "Niger", "NE", "NER", 562, 16f),
    NG(Continent.AF, "Nigeria", "NG", "NGA", 566, 10f),
    NU(Continent.AF, "Niue", "NU", "NIU", 570, -19.0333f),
    NF(Continent.AF, "Norfolk Island", "NF", "NFK", 574, -29.0333f),
    MP(Continent.AF, "Northern Mariana Islands", "MP", "MNP", 580, 15.2f),
    NO(Continent.AF, "Norway", "NO", "NOR", 578, 62f),
    OM(Continent.AF, "Oman", "OM", "OMN", 512, 21f),
    PK(Continent.AF, "Pakistan", "PK", "PAK", 586, 30f),
    PW(Continent.AF, "Palau", "PW", "PLW", 585, 7.5f),
    PS(Continent.AF, "Palestinian Territory, Occupied", "PS", "PSE", 275, 32f),
    PA(Continent.AF, "Panama", "PA", "PAN", 591, 9f),
    PG(Continent.AF, "Papua New Guinea", "PG", "PNG", 598, -6f),
    PY(Continent.AF, "Paraguay", "PY", "PRY", 600, -23f),
    PE(Continent.AF, "Peru", "PE", "PER", 604, -10f),
    PH(Continent.AF, "Philippines", "PH", "PHL", 608, 13f),
    PN(Continent.AF, "Pitcairn", "PN", "PCN", 612, -24.7f),
    PL(Continent.AF, "Poland", "PL", "POL", 616, 52f),
    PT(Continent.AF, "Portugal", "PT", "PRT", 620, 39.5f),
    PR(Continent.AF, "Puerto Rico", "PR", "PRI", 630, 18.25f),
    QA(Continent.AF, "Qatar", "QA", "QAT", 634, 25.5f),
    RE(Continent.AF, "Réunion", "RE", "REU", 638, -21.1f),
    RO(Continent.AF, "Romania", "RO", "ROU", 642, 46f),
    RU(Continent.AF, "Russia", "RU", "RUS", 643, 60f),
    RW(Continent.AF, "Rwanda", "RW", "RWA", 646, -2f),
    SH(Continent.AF, "Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", 654, -15.9333f),
    KN(Continent.AF, "Saint Kitts and Nevis", "KN", "KNA", 659, 17.3333f),
    LC(Continent.AF, "Saint Lucia", "LC", "LCA", 662, 13.8833f),
    PM(Continent.AF, "Saint Pierre and Miquelon", "PM", "SPM", 666, 46.8333f),
    VC(Continent.AF, "St. Vincent and the Grenadines", "VC", "VCT", 670, 13.25f),
    WS(Continent.AF, "Samoa", "WS", "WSM", 882, -13.5833f),
    SM(Continent.AF, "San Marino", "SM", "SMR", 674, 43.7667f),
    ST(Continent.AF, "Sao Tome and Principe", "ST", "STP", 678, 1f),
    SA(Continent.AF, "Saudi Arabia", "SA", "SAU", 682, 25f),
    SN(Continent.AF, "Senegal", "SN", "SEN", 686, 14f),
    RS(Continent.AF, "Serbia", "RS", "SRB", 688, 44f),
    SC(Continent.AF, "Seychelles", "SC", "SYC", 690, -4.5833f),
    SL(Continent.AF, "Sierra Leone", "SL", "SLE", 694, 8.5f),
    SG(Continent.AF, "Singapore", "SG", "SGP", 702, 1.3667f),
    SK(Continent.AF, "Slovakia", "SK", "SVK", 703, 48.6667f),
    SI(Continent.AF, "Slovenia", "SI", "SVN", 705, 46f),
    SB(Continent.AF, "Solomon Islands", "SB", "SLB", 90, -8f),
    SO(Continent.AF, "Somalia", "SO", "SOM", 706, 10f),
    ZA(Continent.AF, "South Africa", "ZA", "ZAF", 710, -29f),
    GS(Continent.AF, "South Georgia and the South Sandwich Islands", "GS", "SGS", 239, -54.5f),
    ES(Continent.AF, "Spain", "ES", "ESP", 724, 40f),
    LK(Continent.AF, "Sri Lanka", "LK", "LKA", 144, 7f),
    SD(Continent.AF, "Sudan", "SD", "SDN", 736, 15f),
    SR(Continent.AF, "Suriname", "SR", "SUR", 740, 4f),
    SJ(Continent.AF, "Svalbard and Jan Mayen", "SJ", "SJM", 744, 78f),
    SZ(Continent.AF, "Swaziland", "SZ", "SWZ", 748, -26.5f),
    SE(Continent.AF, "Sweden", "SE", "SWE", 752, 62f),
    CH(Continent.AF, "Switzerland", "CH", "CHE", 756, 47f),
    SY(Continent.AF, "Syrian Arab Republic", "SY", "SYR", 760, 35f),
    TW(Continent.AF, "Taiwan", "TW", "TWN", 158, 23.5f),
    TJ(Continent.AF, "Tajikistan", "TJ", "TJK", 762, 39f),
    TZ(Continent.AF, "Tanzania, United Republic of", "TZ", "TZA", 834, -6f),
    TH(Continent.AF, "Thailand", "TH", "THA", 764, 15f),
    TL(Continent.AF, "Timor-Leste", "TL", "TLS", 626, -8.55f),
    TG(Continent.AF, "Togo", "TG", "TGO", 768, 8f),
    TK(Continent.AF, "Tokelau", "TK", "TKL", 772, -9f),
    TO(Continent.AF, "Tonga", "TO", "TON", 776, -20f),
    TT(Continent.AF, "Trinidad and Tobago", "TT", "TTO", 780, 11f),
    TN(Continent.AF, "Tunisia", "TN", "TUN", 788, 34f),
    TR(Continent.AF, "Turkey", "TR", "TUR", 792, 39f),
    TM(Continent.AF, "Turkmenistan", "TM", "TKM", 795, 40f),
    TC(Continent.AF, "Turks and Caicos Islands", "TC", "TCA", 796, 21.75f),
    TV(Continent.AF, "Tuvalu", "TV", "TUV", 798, -8f),
    UG(Continent.AF, "Uganda", "UG", "UGA", 800, 1f),
    UA(Continent.AF, "Ukraine", "UA", "UKR", 804, 49f),
    AE(Continent.AF, "United Arab Emirates", "AE", "ARE", 784, 24f),
    GB(Continent.AF, "United Kingdom", "GB", "GBR", 826, 54f),
    US(Continent.AF, "United States", "US", "USA", 840, 38f),
    UM(Continent.AF, "United States Minor Outlying Islands", "UM", "UMI", 581, 19.2833f),
    UY(Continent.AF, "Uruguay", "UY", "URY", 858, -33f),
    UZ(Continent.AF, "Uzbekistan", "UZ", "UZB", 860, 41f),
    VU(Continent.AF, "Vanuatu", "VU", "VUT", 548, -16f),
    VE(Continent.AF, "Venezuela", "VE", "VEN", 862, 8f),
    VN(Continent.AF, "Vietnam", "VN", "VNM", 704, 16f),
    VG(Continent.AF, "Virgin Islands, British", "VG", "VGB", 92, 18.5f),
    VI(Continent.AF, "Virgin Islands, U.S.", "VI", "VIR", 850, 18.3333f),
    WF(Continent.AF, "Wallis and Futuna", "WF", "WLF", 876, -13.3f),
    EH(Continent.AF, "Western Sahara", "EH", "ESH", 732, 24.5f),
    XK(Continent.AF, "Kosovo", "XK", "XKX", 43, 20.9f),
    YE(Continent.AF, "Yemen", "YE", "YEM", 887, 15f),
    ZM(Continent.AF, "Zambia", "ZM", "ZMB", 894, -15f),
    ZW(Continent.AF, "Zimbabwe", "ZW", "ZWE", 716, -20f)

    Country(final Continent continent, final String name, final String alphaIso2, final String alphaIso3, final int latitude, final float longitude) {
        this.continent = continent
        this.name = name
        this.alphaIso2 = alphaIso2
        this.alphaIso3 = alphaIso3
        this.latitude = latitude
        this.longitude = longitude
    }
    final Continent continent
    final String name
    final String alphaIso2
    final String alphaIso3
    final float latitude
    final double longitude

    String getAsset() {
        "/assets/icons/countries/${alphaIso2.toLowerCase()}.webp"
    }

    static Country fromAlphaIso3(final String alphaIso3) {
        if (alphaIso3) {
            final String a3 = alphaIso3.toLowerCase()
            values().find {it.alphaIso3.toLowerCase() == a3 }
        } else null
    }

    static Country fromAlphaIso2(final String alphaIso2) {
        if (alphaIso2) {
            final String a2 = alphaIso2.toLowerCase()
            values().find {it.alphaIso2.toLowerCase() == a2 }
        } else null
    }

    String nameForLanguage(String lang = "en") {
        def locale = new Locale("", this.toString())
        return locale.getDisplayCountry(new Locale(lang, this.toString()))
    }

    static EnumOption[] getEnumOptions() {
        EnumOption[] res = new EnumOption[values().size()]
        int i = 0
        for (def option in values()) {
            res[i++] = new EnumOption(option.toString(), option.name)
        }
        return res
    }

}

enum Language {
    FR("fr", "fr", "French", Locale.FRENCH),
    EN("en", "en", "US/English", Locale.US),
    DE("de", "de", "German", Locale.GERMAN),
    ES("es", "es", "Spanish"),
    RU("ru", "ru", "Russian"),
    CN("cn", "cn", "Chinese")

    Language(String codeLanguage, String iso2, String labeling, Locale locale = null) {
        this.codeLanguage = codeLanguage
        this.iso2 = iso2
        this.labeling = labeling
        this.locale = locale
    }
    final String codeLanguage
    final String iso2
    final String labeling
    final Locale locale

    String getAsset() {
        "/assets/icons/countries/${iso2}.webp"
    }

}