package crew.config

enum BusinessUnit {
    DIRECTION,
    FINANCE,
    MARKETING,
    DESIGN,
    RD,
    ENGINEERING,
    HR,
    IT,
    SALES,
    PURCHASE,
    MANUFACTURING,
    SERVICE,
    RQE,
    OTHER
}

enum Position {
    BoardOfDirectors,
    C_Level,
    Shareholders,
    Managers,
    Supervisors,
    FrontLineEmployees,
    QualityControl,
    HumanResources,
    AccountingStaff,
    MarketingStaff,
    PurchasingStaff,
    ShippingAndReceivingStaff,
    OfficeManager,
    Receptionist
}

enum LeadershipTitle {
    TeamLeader,
    Manager,
    AssistantManager,
    Executive,
    Director,
    Coordinator,
    Administrator,
    Controller,
    Officer,
    Organizer,
    Supervisor,
    Superintendent,
    Head,
    Overseer,
    Chief,
    Foreman,
    Principal,
    President,
    Lead,
}

enum BusinessOwnerTitle {
    CEO,
    Proprietor,
    Principal,
    Owner,
    President,
    Founder,
    Administrator,
    Director,
    ManagingPartner,
    ManagingMember
}

enum Title {
    CEO("Chief Executive Officer"),
    COO("Chief Operating Officer"),
    CFO("Chief Financial Officer"),
    CIO("Chief Information Officer", BusinessUnit.IT),
    CTO("Chief Technology Officer"),
    CMO("Chief Marketing Officer"),
    CHRO("Chief Human Resources Officer"),
    CDO("Chief Data Officer"),
    CPO("Chief Product Officer"),
    CCO("Chief Customer Officer"),
    ComputerScientist(BusinessUnit.IT),
    ITProfessional(BusinessUnit.IT),
    UXDesigner(BusinessUnit.IT),
    SQLDeveloper(BusinessUnit.IT),
    WebDesigner(BusinessUnit.IT),
    WebDesignerMkg(BusinessUnit.MARKETING),
    WebDeveloper(BusinessUnit.IT),
    HelpDeskWorker(BusinessUnit.IT),
    SoftwareEngineer(BusinessUnit.IT),
    DataEntry(BusinessUnit.IT),
    DevOpsEngineer(BusinessUnit.IT),
    ComputerProgrammer(BusinessUnit.IT),
    NetworkAdministrator(BusinessUnit.IT),
    InformationSecurityAnalyst(BusinessUnit.IT),
    ArtificialIntelligenceEngineer(BusinessUnit.IT),
    CloudArchitect(BusinessUnit.IT),
    ITManager(BusinessUnit.IT),
    TechnicalSpecialist(BusinessUnit.IT),
    ApplicationDeveloper(BusinessUnit.IT),
    MarketingSpecialist(BusinessUnit.MARKETING),
    MarketingManager(BusinessUnit.MARKETING),
    MarketingDirector(BusinessUnit.MARKETING),
    GraphicDesigner(BusinessUnit.MARKETING),
    MarketingResearchAnalyst(BusinessUnit.MARKETING),
    MarketingCommunicationsManager(BusinessUnit.MARKETING),
    MarketingConsultant(BusinessUnit.MARKETING),
    ProductManager(BusinessUnit.MARKETING),
    PublicRelations(BusinessUnit.MARKETING),
    SocialMediaAssistant(BusinessUnit.MARKETING),
    BrandManager(BusinessUnit.MARKETING),
    SEOManager(BusinessUnit.MARKETING),
    ContentMarketingManager(BusinessUnit.MARKETING),
    Copywriter(BusinessUnit.MARKETING),
    MediaBuyer(BusinessUnit.MARKETING),
    DigitalMarketingManager(BusinessUnit.MARKETING),
    eCommerceMarketingSpecialist(BusinessUnit.MARKETING),
    BrandStrategist(BusinessUnit.MARKETING),
    VicePresidentOfMarketing(BusinessUnit.MARKETING),
    MediaRelationsCoordinator(BusinessUnit.MARKETING),
    SalesAssociate(BusinessUnit.SALES),
    SalesRepresentative(BusinessUnit.SALES),
    SalesManager(BusinessUnit.SALES),
    RetailWorker(BusinessUnit.SALES),
    StoreManager(BusinessUnit.SALES),
    RealEstateBroker(BusinessUnit.SALES),
    Cashier(BusinessUnit.SALES),
    AccountExecutive(BusinessUnit.SALES),
    AccountManager(BusinessUnit.SALES),
    AreaSalesManager(BusinessUnit.SALES),
    DirectSalesperson(BusinessUnit.SALES),
    DirectorOfInsideSales(BusinessUnit.SALES),
    OutsideSalesManager(BusinessUnit.SALES),
    SalesAnalyst(BusinessUnit.SALES),
    MarketDevelopmentManager(BusinessUnit.SALES),
    B2BSalesSpecialist(BusinessUnit.SALES),
    MerchandisingAssociate(BusinessUnit.SALES),
    ConstructionWorker(BusinessUnit.MANUFACTURING),
    Taper(BusinessUnit.MANUFACTURING),
    Plumber(BusinessUnit.MANUFACTURING),
    HeavyEquipmentOperator(BusinessUnit.MANUFACTURING),
    EquipmentCleaner(BusinessUnit.MANUFACTURING),
    Carpenter(BusinessUnit.MANUFACTURING),
    Electrician(BusinessUnit.MANUFACTURING),
    Painter(BusinessUnit.MANUFACTURING),
    Welder(BusinessUnit.MANUFACTURING),
    Handyman(BusinessUnit.MANUFACTURING),
    Boilermaker(BusinessUnit.MANUFACTURING),
    CraneOperator(BusinessUnit.MANUFACTURING),
    BuildingInspector(BusinessUnit.MANUFACTURING),
    SheetMetalWorker(BusinessUnit.MANUFACTURING),
    IronWorker(BusinessUnit.MANUFACTURING),
    Mason(BusinessUnit.MANUFACTURING),
    Roofer(BusinessUnit.MANUFACTURING),
    SolarPhotovoltaicInstaller(BusinessUnit.MANUFACTURING),
    WellDriller(BusinessUnit.MANUFACTURING),
    VirtualAssistant(BusinessUnit.SERVICE),
    CustomerService(BusinessUnit.SERVICE),
    CustomerSupport(BusinessUnit.SERVICE),
    Concierge(BusinessUnit.SERVICE),
    HelpDesk(BusinessUnit.SERVICE),
    CustomerServiceManager(BusinessUnit.SERVICE),
    TechnicalSupportSpecialist(BusinessUnit.SERVICE),
    AccountRepresentative(BusinessUnit.SERVICE),
    ClientServiceSpecialist(BusinessUnit.SERVICE),
    CustomerCareAssociate(BusinessUnit.SERVICE),
    OperationsManager(BusinessUnit.DIRECTION),
    OperationsAssistant(BusinessUnit.DIRECTION),
    OperationsCoordinator(BusinessUnit.DIRECTION),
    OperationsAnalyst(BusinessUnit.DIRECTION),
    OperationsDirector(BusinessUnit.DIRECTION),
    VicePresidentOfOperations(BusinessUnit.DIRECTION),
    OperationsProfessional(BusinessUnit.DIRECTION),
    ScrumMaster(BusinessUnit.DIRECTION),
    ContinuousImprovementLead(BusinessUnit.DIRECTION),
    ContinuousImprovementConsultant(BusinessUnit.DIRECTION),
    CreditAuthorizer(BusinessUnit.FINANCE),
    BenefitsManager(BusinessUnit.FINANCE),
    CreditCounselor(BusinessUnit.FINANCE),
    Accountant(BusinessUnit.FINANCE),
    Bookkeeper(BusinessUnit.FINANCE),
    AccountingAnalyst(BusinessUnit.FINANCE),
    AccountingDirector(BusinessUnit.FINANCE),
    AccountsPayable(BusinessUnit.FINANCE),
    Auditor(BusinessUnit.FINANCE),
    BudgetAnalyst(BusinessUnit.FINANCE),
    Controller(BusinessUnit.FINANCE),
    FinancialAnalyst(BusinessUnit.FINANCE),
    FinanceManager(BusinessUnit.FINANCE),
    Economist(BusinessUnit.FINANCE),
    PayrollManager(BusinessUnit.FINANCE),
    PayrollClerk(BusinessUnit.FINANCE),
    FinancialPlanner(BusinessUnit.FINANCE),
    FinancialServicesRepresentative(BusinessUnit.FINANCE),
    FinanceDirector(BusinessUnit.FINANCE),
    CommercialLoanOfficer(BusinessUnit.FINANCE),
    Engineer(BusinessUnit.ENGINEERING),
    MechanicalEngineer(BusinessUnit.ENGINEERING),
    CivilEngineer(BusinessUnit.ENGINEERING),
    ElectricalEngineer(BusinessUnit.ENGINEERING),
    AssistantEngineer(BusinessUnit.ENGINEERING),
    ChemicalEngineer(BusinessUnit.ENGINEERING),
    ChiefEngineer(BusinessUnit.ENGINEERING),
    Drafter(BusinessUnit.ENGINEERING),
    EngineeringTechnician(BusinessUnit.ENGINEERING),
    GeologicalEngineer(BusinessUnit.ENGINEERING),
    BiologicalEngineer(BusinessUnit.ENGINEERING),
    MaintenanceEngineer(BusinessUnit.ENGINEERING),
    MiningEngineer(BusinessUnit.ENGINEERING),
    NuclearEngineer(BusinessUnit.ENGINEERING),
    PetroleumEngineer(BusinessUnit.ENGINEERING),
    PlantEngineer(BusinessUnit.ENGINEERING),
    ProductionEngineer(BusinessUnit.ENGINEERING),
    QualityEngineer(BusinessUnit.ENGINEERING),
    SafetyEngineer(BusinessUnit.ENGINEERING),
    SalesEngineer(BusinessUnit.ENGINEERING),
    Researcher(BusinessUnit.RD),
    ResearchAssistant(BusinessUnit.RD),
    DataAnalyst(BusinessUnit.RD),
    BusinessAnalyst(BusinessUnit.RD),
    TitleResearcher(BusinessUnit.RD),
    MarketResearcher(BusinessUnit.RD),
    TitleAnalyst(BusinessUnit.RD),
    MedicalResearcher(BusinessUnit.RD),
    OTHER(BusinessUnit.OTHER)

    Title(final String enTitle = null, final BusinessUnit businessUnit = BusinessUnit.OTHER) {
        title = enTitle ?: this.toString()
        this.businessUnit = businessUnit
    }

    Title(final BusinessUnit businessUnit) {
        title = this.toString()
        this.businessUnit = businessUnit
    }

    final String title
    final BusinessUnit businessUnit
}